#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f ".env.local" ]; then
    set -a
    # shellcheck disable=SC1091
    . ".env.local"
    set +a
fi

if [ -z "${TRAKT_CLIENT_ID:-}" ]; then
    echo "错误: 请先在 .env.local 中配置 TRAKT_CLIENT_ID=your_client_id"
    exit 1
fi

LOCAL_XCCONFIG="MyTV/Config/Local.xcconfig"
mkdir -p "$(dirname "$LOCAL_XCCONFIG")"

TEAM_ID="${DEVELOPMENT_TEAM:-}"
if [ -z "$TEAM_ID" ] && [ -f "MyTV.xcodeproj/project.pbxproj" ]; then
    TEAM_ID="$(
        awk -F'= ' '/DEVELOPMENT_TEAM =/ {
            gsub(/[;[:space:]]/, "", $2)
            print $2
            exit
        }' "MyTV.xcodeproj/project.pbxproj"
    )"
fi

{
    printf '// Generated by scripts/sync-local-xcconfig.sh\n'
    printf '// This file is ignored by git. Do not commit local secrets.\n'
    printf 'TRAKT_CLIENT_ID = %s\n' "$TRAKT_CLIENT_ID"
    if [ -n "$TEAM_ID" ]; then
        printf 'DEVELOPMENT_TEAM = %s\n' "$TEAM_ID"
    fi
} > "$LOCAL_XCCONFIG"

echo "已写入 $LOCAL_XCCONFIG"
if [ -n "$TEAM_ID" ]; then
    echo "已包含 DEVELOPMENT_TEAM"
else
    echo "提示: 如需真机签名固定 Team，可在 .env.local 中加入 DEVELOPMENT_TEAM=your_team_id 后重跑本脚本"
fi
